apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: kibana
  namespace: monitoring-system
spec:
  version: 8.13.4
  count: 1
  elasticsearchRef:
    name: elasticsearch
    namespace: monitoring-system
  http:
    service:
      spec:
        type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
