apiVersion: logstash.k8s.elastic.co/v1alpha1
kind: Logstash
metadata:
  name: logstash
  namespace: monitoring-system
spec:
  count: 1
  elasticsearchRefs:
    - name: elasticsearch
      namespace: monitoring-system
      clusterName: elasticsearch
  version: 8.13.4
  pipelines:
    - pipeline.id: main
      config.string: |
        input {
          beats {
            port => 5044
          }
        }
        filter {
          json {
            source => "message"
          }
        }
        output {
          elasticsearch {
            hosts => ["${QS_ES_HOSTS}"]
            user => "${QS_ES_USER}"
            password => "${QS_ES_PASSWORD}"
            ssl_verification_mode => "none"
            index => "kubernetes-%{+YYYY.MM.dd}"
          }
        }
  podTemplate:
    spec:
      containers:
        - name: logstash
          resources:
            limits:
              memory: "1024Mi"
          env:
            - name: QS_ES_HOSTS
              value: "http://elasticsearch-es-http.monitoring-system.svc.cluster.local:9200"
            - name: QS_ES_USER
              value: "elastic"
            - name: QS_ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-es-elastic-user
                  key: elastic
  services:
    - name: filebeat
      service:
        spec:
          type: NodePort
          ports:
            - name: filebeat
              port: 5044
              protocol: TCP
              targetPort: 5044
